name: Build dlib for Windows

on:
  workflow_dispatch:
    inputs:
      python-version:
        description: 'Python version (e.g., 3.11)'
        required: true
        default: '3.11'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
          architecture: x64
      
      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1.3.1
      
      - name: Install CMake
        uses: lukka/run-cmake@v3.7.0  # 安装系统级 CMake
      
      - name: Install build dependencies
        run: |
          pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
          pip install --upgrade pip wheel setuptools --retries 5
      
      - name: Build dlib wheel
        run: |
          python -m pip wheel dlib --no-binary :all: -w dist/
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dlib-wheel
          path: dist/*.whl
